In [6]:
import numpy as np

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
# get a specific element [r,c]
a[1,5]

np.int64(13)

In [8]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [11]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [14]:
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [15]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [18]:
# get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [ ]:
# replace
b[:,1,:] = [[9],[8]]

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


ValueError: could not broadcast input array from shape (2,1) into shape (1,2)