In [4]:
# all 0s matrix
import numpy as np
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [3]:
# any other number
import numpy as np
a = np.full((2,2), 99)
a

array([[99, 99],
       [99, 99]])

In [4]:
# any other number (full_like)
np.full_like(a, 4) 

array([[4, 4],
       [4, 4]])

In [ ]:
# any other number (full_like)
np.full_like(a, 4) 

array([[4, 4],
       [4, 4]])

In [27]:
#random decimal numbers 
np.random.rand(4,2)

array([[0.1821674 , 0.08516916],
       [0.42275045, 0.18736927],
       [0.31078709, 0.77304098],
       [0.05590673, 0.34023291]])

In [37]:
#random integers values
np.random.randint(-4,7, size=(3,3))

array([[ 2, -3, -3],
       [ 4,  5,  5],
       [-2, -2,  5]], dtype=int32)

In [ ]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [57]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be caruful when copying arrays!!

In [65]:
a= np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]
