#### LINEAR ALGEBRA

In [4]:
import numpy as np

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# fins the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)