#### Load Data from File

In [5]:
import numpy as np

filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.],
       [  8.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.],
       [  4.,   5.,   6.,   7.,   0.,  11.,  12.,  13.,  14.,  15.,  16.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.],
       [  2.,   9.,   8.,   7.,   1.,  76.,  88.,  99.,   0.,   1.,   2.]])

#### Boolean Masking and Advanced indexing

In [ ]:
filedata >= 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False],
       [False, False, False, False, False,  True,  True,  True, False,
        False, False]])

In [7]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.,  99.])

In [9]:
# you can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [10]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [11]:
np.all(filedata > 50, axis=1)

array([False, False, False, False, False, False])

In [13]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False],
       [False, False, False, False, False,  True,  True,  True, False,
        False, False]])

In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True],
       [ True,  True,  True,  True,  True, False, False, False,  True,
         True,  True]])