In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# get dimension
a.ndim

2

In [12]:
# get dimension
b.ndim

2

In [13]:
# get shape
a.shape

(3,)

In [ ]:
# get shape
b.shape

(2, 3)

In [15]:
#get type
a.dtype

dtype('int64')

In [ ]:
#get size
a.itemsize

8

In [18]:
# get total size
a.nbytes

24