In [6]:
import numpy as np 

v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])
v3 = np.array([11,12,13,14,15])
v4 = np.array([16,17,18,19,20])
v5 = np.array([21,22,23,24,25])
v6 = np.array([26,27,28,29,30])

a = np.vstack([v1,v2,v3,v4,v5,v6])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
a[2:4,0:2]


array([[11, 12],
       [16, 17]])

In [17]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [26]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])