In [1]:
import numpy as np

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.max(stats, axis = 1)

array([3, 6])

In [3]:
np.min(stats, axis=1)

array([1, 4])

In [7]:
np.sum(stats, axis=0)

array([5, 7, 9])